# Generated by Django 3.1.6 on 2021-02-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('first_transaction_date', models.DateTimeField(null=True)),
                ('latest_transaction_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
